Journal/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = "Journal"

urlpatterns = [
    path('Journal', views.landing_page, name='landing_page'),
    path('login', views.login_user, name='login'),
    path('logout', views.user_logout, name='logout'),
    path('register', views.register, name='register'),
    path('Journal/entry/<int:pk>', views.entry, name='entry'),
    path('Journal/entry_list/<int:pk>', views.entry_list, name='entry_list'),
    path('Journal/entry_list/edit_entry/<int:entry_id>', views.entry_edit, name='entry_edit'),
    path('Journal/entry_list/edit_entry/<int:entry_id>/update', views.entry_update, name='entry_update'),
    path('Journal/entry_list/<int:pk>/delete/<int:entry_id>', views.entry_delete, name='entry_delete'),
    path('Journal/entry_list/<int:pk>/delete/<int:entry_id>/confirm', views.delete_confirm, name='delete_confirm'),
]

journeyJournal/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Journal.urls')),
]

Journal/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator


class Entry(models.Model):
    title = models.CharField(max_length = 80)
    location = models.CharField(max_length = 80)
    content =  models.TextField(blank=True)
    date = models.DateField()
    image =  models.CharField(max_length = 300)
    customer = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
    )

    def __str__(self):
        return f'{self.title}'
    
    

Journal/forms.py
from django.contrib.auth.models import User
from django import forms
from Journal.models import *

class UserForm(forms.ModelForm):
    '''Form class to create a new user
    
    Author: Austin
    '''
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'first_name', 'last_name',)

class DateInput(forms.DateInput):
    input_type = 'date'


class EntryForm(forms.ModelForm):
    '''Form class to create a new entry
    
    Author: Austin
    '''
    class Meta:
        model = Entry
        fields = ('title', 'location', 'content', 'date', 'image')
        widgets = {
            'date': DateInput(),
        }




Journal/views/entry_views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from Journal.forms import EntryForm
from Journal.models import *



def entry(request, pk):

    if request.method == 'GET':
        entry_form = EntryForm()
        context = {'entry_form': entry_form}
        return render(request, 'entry_add.html', context)

    if request.method == 'POST':
    
        title = request.POST['title']
        location = request.POST['location']
        content = request.POST['content']
        date = request.POST['date']
        image = request.POST['image']
      
        
        new_entry = Entry(title=title, location=location, content=content, date=date, image=image, customer_id=request.user.id)
        new_entry.save()

        return HttpResponseRedirect(reverse('Journal:entry_list', args=(request.user.id,)))

        

def entry_list(request, pk):
    
    entry_list = Entry.objects.filter(customer_id=pk).order_by('date')
    context = {'entry_list': entry_list}
    return render(request, 'entry_list.html', context)


def entry_edit(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    edit_form =  EntryForm(initial={'title': entry.title, 'location': entry.location, 'content': entry.content, 'date':entry.date, 'image':entry.image, 'customer_id':request.user.id})
    context = {"entry": entry, "edit_form": edit_form}
    return render(request, 'entry_edit_form.html', context)



def entry_update(request, entry_id):
    entry_details = Entry(id=request.POST['entry_id'],title=request.POST['title'], location=request.POST['location'], content=request.POST['content'], date=request.POST['date'], image=request.POST['image'], customer_id=request.user.id)
    entry_details.save()
    return HttpResponseRedirect(reverse('Journal:entry_list', args=(request.user.id,)))



def delete_confirm(request, pk, entry_id):
    entry_to_delete = Entry.objects.get(pk=entry_id)
    context ={"entry": entry_to_delete}
    return render(request, 'confirm_entrty_delete.html', context)



def entry_delete(request, pk, entry_id):
    deleted_entry = Entry.objects.get(pk=request.POST['entry_id'])
    deleted_entry.delete()
    return HttpResponseRedirect(reverse('Journal:entry_list', args=(request.user.id,)))




Journal/views/landing_views.py
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.template import RequestContext
from django.urls import reverse
from Journal.models import *




def landing_page(request):
    """Renders main landing page for Journal 

    Model:None

    Template:index.html

    """
    return render(request, 'index.html')

Journal/views/user_views.py
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render
from django.template import RequestContext
from Journal.models import *
from Journal.forms import UserForm



def register(request):
    '''Handles the creation of a new user for authentication

    Method arguments:
      request -- The full HTTP request object
    '''

    # A boolean value for telling the template whether the registration was successful.
    # Set to False initially. Code changes value to True when registration succeeds.
    registered = False

    # Create a new user as well as a new customer at the same time
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        # confirm_password = request.POST['confirm_password']
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            return login_user(request)
    
        else:
            print("not valid user form")


    elif request.method == 'GET':
        user_form = UserForm()
        context = {'user_form': user_form}
        template_name = 'register.html'
        return render(request, template_name, context)


def login_user(request):
    '''Handles the creation of a new user for authentication

    Method arguments:
      request -- The full HTTP request object
    '''

    # Obtain the context for the user's request.
    context = RequestContext(request)

    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':

        # Use the built-in authenticate method to verify
        username=request.POST['username']
        password=request.POST['password']
        authenticated_user = authenticate(username=username, password=password)

        # If authentication was successful, log the user in
        if authenticated_user is not None:
            login(request=request, user=authenticated_user)
            return HttpResponseRedirect('Journal')

        else:
            # Bad login details were provided. So we can't log the user in.
            print("Invalid login details: {}, {}".format(username, password))
            return HttpResponse("Invalid login details supplied.")


    return render(request, 'login.html', {}, context)

# Use the login_required() decorator to ensure only those logged in can access the view.
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)
    return HttpResponseRedirect('Journal')

Journal/templates/confirm_entrty_delete.html
{% extends "index.html" %}
{% load staticfiles %}

{% block content %}

<h3>Are you sure you want to delete entry, {{entry.title}}</h3>
<div class="list_buttons"> 

    <button class="btn btn-primary"><a href="{% url 'Journal:entry_list' user.id %}">Cancel</a></button>
    <form class="extra-marg" action="{% url 'Journal:entry_delete' entry.customer_id entry.id %}" method="POST">
        
        {% csrf_token %}
        
        <input type="hidden" value="{{entry.id}}" name="entry_id">
        <input class="btn btn-danger" type="submit" value="Delete">
    </form>
</div>

{% endblock %}

Journal/templates/entry_add.html
{% extends "index.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}


{% block content %}

<h2>Record a New Entry</h2>
<form class="entry_form" method="post" action="{% url 'Journal:entry' user.id %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{entry_form|crispy}}

    <input class="btn btn-primary" type='submit' value="Submit"/>
</form>
{% endblock content %}

Journal/templates/entry_edit_form.html
{% extends "index.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}

<h2>Edit Your Entry, {{entry.title}}</h2>
<form class="entry_form" method="POST" action="{% url 'Journal:entry_update' user.id %}" enctype="multipart/form-data">
    {% csrf_token %}

    {{edit_form|crispy}}
    <input type="hidden" value="{{entry.id}}" name="entry_id">

    <input class="btn btn-primary" type='submit' value="Submit" />
</form>
{% endblock content %}

Journal/templates/entry_list.html
{% extends "index.html" %}
{% load staticfiles %}

{% block content %}

{% if entry_list %}
<h2 class="title">{{user.username}}'s Journey Journal </h2>
{% for entry in entry_list %}
<div class='entry_div'>
    <div class="entry_heading">
        <h4>{{entry.title}}</h4>
        <h6>{{entry.location}} | {{entry.date}}</h6>
    </div>
    <div class='entry_content'>
        <p>{{entry.content}}</p>
        <div>
            <img src={{entry.image}} alt={{entry.title}}>
        </div>
    </div>
    <div class="list_buttons">
        <button class="btn btn-primary"><a href="{% url 'Journal:entry_edit' entry.id %}">Edit</a></button>
        <button class="btn btn-danger"><a
                href="{% url 'Journal:delete_confirm' entry.customer_id entry.id %}">Delete</a></button>
    </div>
</div>
{% endfor %}

{% else %}
<p> NO ENTRIES YET </p>

{% endif %}

{% endblock %}

Journal/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'Journal/index.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Journey Journal</title>
</head>

<body>
    {% block nav %}
    {% include "nav.html" %}
    {% endblock nav %}

    {% block content %}
    {% if user.is_authenticated %}
    <h1 class='title'>Welcome To Journey Journal {{ user.username}}!</h1>
    <div class='moto'>
        <p>Explore.</p>
        <p>Record.</p>
        <p>Repeat.</p>
    </div>
    {% else %}
    <h1 class="title">Welcome To Journey Journal</h1>
    <h2>Let's Get Started</h2>
    <div class='not_loged'>
        <div class='moto'>
            <p>Explore.</p>
            <p>Record.</p>
            <p>Repeat.</p>
        </div>
        <div class="list_buttons">
            <button class="btn btn-primary"><a href="{% url 'Journal:login' %}">Login</a></button>
            <button class="btn btn-secondary"><a href="{% url 'Journal:register' %}">Register</a></button>
        </div>
    </div>

    {% endif %}

    {% endblock content %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

Journal/templates/login.html
{% extends "index.html" %}
{% load staticfiles %}

{% block content %}

<h1>Login To Journey Journal</h1>

<form id="login_form" method="post" action="{% url 'Journal:login' %}">
    {% csrf_token %}
    Username: <input type="text" name="username" value="" size="50" />
    <br />
    Password: <input type="password" name="password" value="" size="50" />
    <br />
    <input class="register" type="submit" value="Login" />
</form>

{% endblock content %}

Journal/templates/nav.html
{% load staticfiles %}

<!-- Basic block for navbar -->
{% block nav %}
{% if user.is_authenticated %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark nav_flex">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <ul class="navbar-nav mr-auto">
            <li>
                <a class="navbar-brand" href="{% url 'Journal:landing_page' %}">Journey Journal</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Journal:entry' user.id %}">Entry</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Journal:entry_list' user.id %}">View Journal</a>
            </li>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Journal:logout' %}">Logout</a>
            </li>
        </ul>
    </div>
</nav>

{% else %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark nav_flex">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <ul class="navbar-nav mr-auto">

            <li>
                <a class="navbar-brand" href="{% url 'Journal:landing_page' %}">Journey Journal</a>
            </li>
        </ul>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Journal:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Journal:register' %}">Register</a>
            </li>
        </ul>
    </div>
    </div>
</nav>
{% endif %}

{% endblock %}

Journal/templates/register.html
{% extends "index.html" %}
{% load staticfiles %}

{% block content %}

{% if registered %}
<strong>Thank you for registering!</strong>
<a href="{% url 'Journal:landing_page' %}">Return to the homepage.</a><br />
{% else %}
<h1>Register With Journey Journal</h1>

<form id="user_form" method="post" action="{% url 'Journal:register' %}" enctype="multipart/form-data">

    {% csrf_token %}

    {{ user_form.as_p }}

    <input id="register_new" type="submit" name="submit" value="Register" />
</form>
{% endif %}
{% endblock content %}